version: '3.6'

services:
  consul:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8500:8500
    command: agent -server -bind 0.0.0.0 -client 0.0.0.0 -bootstrap-expect 1 -config-file=/tmp/config.json
    volumes:
      - ./config/consul-config.json:/consul/config/config.json
      - ./data:/consul/data
